apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    name: dev
---
# Deployment do website
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  name: web
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: pywebapp
        image: doug2901/pywebapp:1.0
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
---
# Service do website
apiVersion: v1
kind: Service
metadata:
  namespace: dev
  name: web
spec:
  selector:
    app: web
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30000
  type: LoadBalancer